project:
  type: book
  output-dir: _pdf_EN
  resources:
    - "CITATION.cff"
    - images
    - screenshots
    - files
    - "script.js"
    - "webpages.js"
    - "webpages.txt"
    - "headerEN.html"


execute:
  freeze: auto

lang: en

book:
  title: "Histopathology Atlas"
  subtitle: "Atlas of Pathology with Whole Slide Images"
  author:
   - name: "Serdar Balcı"
     url: "https://www.serdarbalci.com"
     affiliation: "Memorial Pathology"
     affiliation-url: "https://patoloji.memorial.com.tr/"
     orcid: "0000-0002-7852-3851"
   - name: Pathologists, Assistants and Technicians
     affiliation: "Memorial Pathology & Other Institutions"
     affiliation-url: "https://www.histopathologyatlas.com/authors.html"
  description: |
    Atlas of Pathology with Whole Slide Images
    Histopathology Atlas and Notes for Medical Students: See and Learn
    Atlas of Histopathology
    Notes for Pathology
    Pathology Lecture Notes and Histopathology Atlas is being prepared from Memorial Pathology Archive and collaborators from other institutions.
  abstract: |
    Atlas of Pathology with Whole Slide Images
    Histopathology Atlas and Notes for Medical Students: See and Learn
    Pathology Lecture Notes and Histopathology Atlas is being prepared from Memorial Pathology Archive and collaborators from other institutions.
    If you want to contribute, please [contact us](https://www.histopathologyatlas.com/contributions.html).
  date: last-modified
  image: images/coverEN.png
  output-file: "Histopathology-Atlas"
  cover-image: images/Histopathology-Atlas-ebook-cover.png
  site-url: https://histopathologyatlas.com/
  search:
    location: navbar
    type: overlay
    copy-button: true
  sidebar:
    style: docked #floating
    background: light
    search: true
    collapsed-level: 1
    pinned: true
  open-graph:
    locale: en_EN
    site-name: Histopathology Atlas
  twitter-card:
    creator: "%40serdarbalci"
    site: "%40patolojinotlari"
  page-navigation: true
  page-footer:
    border: true
    background: light
    left: "Copyright 2022, [patolojiAI](https://www.patolojiai.com/)"
    # right:
    #   - icon: github
    #     href: https://github.com/patolojiatlasi
    #     target: _blank
    #   - icon: github
    #     href: https://github.com/pathologyatlas
    #     target: _blank
    #   - icon: twitter
    #     href: https://twitter.com/patolojinotlari
    #     target: _blank
    #   - icon: globe2
    #     href: https://www.patolojinotlari.com
    #     target: _blank
    #   - icon: globe2
    #     href: https://www.serdarbalci.com
    #     target: _blank

  chapters:
    - text: "Home Page"
      href: index.qmd
    - text: "Introduction"
      href: introduction_pdf_EN.qmd
    - text: "Authors and Contributors"
      href: authors_pdf_EN.qmd
    - part: "---"
    - part: "General Pathology"
      chapters:
        - text: "Techniques Used in Pathology"
          href: techniques_pdf_EN.qmd
        - text: "Intracellular Accumulations"
          href: intracellular-accumulations_pdf_EN.qmd
#         - text: "Extracellular Accumulations"
#           href: extracellular-accumulations_pdf_EN.qmd
#         - text: "Cellular Injury"
#           href: cell-injury_pdf_EN.qmd
# #         - text: "Hemodynamic Disorders"
# #           href: hemodinamik-bozukluklar_pdf_EN.qmd
#         - text: "Ischemia and Necrosis"
#           href: ischemia-necrosis_pdf_EN.qmd
#         - text: "Congestion"
#           href: congestion_pdf_EN.qmd
#         # - text: "Inflammation"
#         #   href: inflamasyon_pdf_EN.qmd
#         - text: "Amyloidosis"
#           href: amyloidosis_pdf_EN.qmd
#         - text: "Repair Mechanisms"
#           href: repair_pdf_EN.qmd
#         - text: "Erosion"
#           href: erosion_pdf_EN.qmd
    # - part: "Inflamation"
    #   chapters:
    #     - text: "Acute inflammation"
    #       href: acute-inflammation_pdf_EN.qmd
    #     - text: "Chronic inflammation"
    #       href: chronic-inflammation_pdf_EN.qmd
    #     - text: "Granulamatous inflammation"
    #       href: granulamatous-inflammation_pdf_EN.qmd
        # - inflamasyon_pdf_EN.qmd
#     - part: "Infectious Diseases"
#       chapters:
#         - text: "Viruses"
#           href: virus_pdf_EN.qmd
#         - text: "Bacteria"
#           href: bacteria_pdf_EN.qmd
#         - text: "Fungi"
#           href: fungi_pdf_EN.qmd
#         - text: "Parasites"
#           href: parasites_pdf_EN.qmd
#     - part: "Neoplasia, Tumor Pathology Basics"
#       chapters:
#         - text: "Benign Tumors"
#           href: benign_pdf_EN.qmd
#         - text: "Hamartoma"
#           href: hamartoma_pdf_EN.qmd
#         - text: "Heterotopia"
#           href: heterotopia_pdf_EN.qmd
#         - text: "Metaplasia"
#           href: metaplasia_pdf_EN.qmd
#         - text: "Carcinogenesis"
#           href: carcinogenesis_pdf_EN.qmd
#         - text: "The properties of Malignant Tumors"
#           href: malignant_pdf_EN.qmd
#         - text: "Metastasis"
#           href: metastasis_pdf_EN.qmd
#         - text: "Tumor Spread to Other Organs"
#           href: tumor-spread_pdf_EN.qmd
#     - part: "Prognostic Morphologic Features of Neoplasms"
#       chapters:
#         - text: "Venous Invasion"
#           href: venous-invasion_pdf_EN.qmd
#         - text: "Extramural Venous Invaasion"
#           href: extramural-venous-invasion_pdf_EN.qmd
#     - part: "Hematopathology"
#       chapters:
# #        - hematopatoloji_pdf_EN.qmd
#         - text: "Hodgkin Lymphoma"
#           href: hodgkin_pdf_EN.qmd
#     - part: "Gastrointestinal System"
#       chapters:
#         - gastro_pdf_EN.qmd
#         - text: "Esophagus"
#           href: esophagus_pdf_EN.qmd
#         - text: "Stomach"
#           href: stomach_pdf_EN.qmd
#         - text: "Gastritis"
#           href: gastritis_pdf_EN.qmd
#         - text: "Duodenum"
#           href: duodenum_pdf_EN.qmd
#         - text: "Colon"
#           href: colon_pdf_EN.qmd
#         - text: "Crohn's Disease"
#           href: crohn_pdf_EN.qmd
#     - part: "Liver"
#       chapters:
#         - text: "Liver Tumors"
#           href: liver_pdf_EN.qmd
#         - text: "Benign Liver Tumors"
#           href: benign-liver-tumors_pdf_EN.qmd
#     - part: "Pancreatobiliary system"
#       chapters:
#         - text: "Pancreas"
#           href: pancreas_pdf_EN.qmd
#         - text: "Pancreas Ductal Adenocarcinoma"
#           href: pdac_pdf_EN.qmd
#         - text: "Gallbladder"
#           href: gallbladder_pdf_EN.qmd
#         - text: "Ampulla of Vater"
#           href: ampulla-vater_pdf_EN.qmd
#     - part: "Lung"
#       chapters:
#         - text: "Neuroendocrine"
#           href: neuroendocrine_pdf_EN.qmd
#     - part: "Mezotel"
#       chapters:
#         - text: "Abdomen"
#           href: mesothelial_pdf_EN.qmd
#     - part: "Gynecopathology"
#       chapters:
#         - text: "Gynecopathology"
#           href: gynecologic_pdf_EN.qmd
#         - text: "Genital System"
#           href: genital_pdf_EN.qmd
#         - text: "Cervix"
#           href: cervix_pdf_EN.qmd
#         - text: "Endometrium"
#           href: endometrium_pdf_EN.qmd
#         - text: "Endometriosis"
#           href: endometriosis_pdf_EN.qmd
#     - part: "Uropathology"
#       chapters:
#         - text: "Uropathology"
#           href: urinary_pdf_EN.qmd
#         - text: "Kidney Tumors / Renal Tumors"
#           href: kidney_pdf_EN.qmd
#         - text: "Prostate"
#           href: prostate_pdf_EN.qmd
#     - part: "Endocrine System"
#       chapters:
#         - text: "Pituitary Adenoma"
#           href: pituitary_pdf_EN.qmd
#     # - part: "Breast"
#     #   chapters:
#     #     - text: "Breast Tumors"
#     #       href: meme.md
#     - part: "Head and Neck"
#       chapters:
#         - text: "Nasopharynx"
#           href: nasopharynx_pdf_EN.qmd
#         - text: "Ear"
#           href: ear_pdf_EN.qmd
#         - text: "Salivary Gland"
#           href: salivary_pdf_EN.qmd
#     - part: "Central Nervous System"
#       chapters:
#         - text: "Glioma"
#           href: glioma_pdf_EN.qmd
#         - text: "Meningioma"
#           href: meningioma_pdf_EN.qmd
#         - text: "Vascular Lesions"
#           href: cns-vascular_pdf_EN.qmd
#     - part: "Bone"
#       chapters:
#         - text: "Bone Tumors"
#           href: bone_pdf_EN.qmd
#     - part: "Soft Tissue"
#       chapters:
#         - text: "Adipose Tissue"
#           href: adipose_pdf_EN.qmd
#     - part: "Pediatric and Perinatal"
#       chapters:
#         - text: "Placenta"
#           href: placenta_pdf_EN.qmd
#     - part: "---"
#     - part: "Special Collections"
#       chapters:
#         - text: "GBDAtlas"
#           href: gbd_pdf_EN.qmd
#         - text: "Hacettepe Case of Month"
#           href: hacettepecom_pdf_EN.qmd
#         - text: "BSAtlas"
#           href: bs_pdf_EN.qmd
#         - text: "ICEtlas"
#           href: ice_pdf_EN.qmd
#         - text: "Similar Websites"
#           href: wsi_pdf_EN.qmd
#     - part: "---"
#     - references_pdf_EN.qmd
#     - part: "---"
#   appendices:
#     # - yonetim-gelistirme.md
#     - text: "Contributions are welcome"
#       href: contributions_pdf_EN.qmd
#     - text: "Comments are welcome"
#       href: comments_pdf_EN.qmd
#     - text: "List"
#       href: listing_pdf_EN.qmd
#     - listing2_pdf_EN.qmd



format:
  pdf:
    toc: true
    toc-depth: 2
    # lof: true
    # lot: true
    number-sections: true
    number-depth: 2
    colorlinks: true
    keep-tex: true
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
#         \usepackage{fvextra}
#         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
#         \areaset[0.50in]{4.5in}{8in}
#         \usepackage{titlesec}
#         \usepackage{svg}
#         \usepackage{transparent}
#         \usepackage{tikzfill}
#         \usepackage{sidenotes}
#         \usepackage{marginnote}
#         \usepackage{changepage}
#     include-before-body:
#       text: |
#         \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
#            showspaces = false,
#            showtabs = false,
#            breaksymbolleft={},
#            breaklines
#            % Note: setting commandchars=\\\{\} here will cause an error
#         }
    include-after-body:
      text: |
        \printindex
    execute:
      warning: false

#    # documentclass: scrbook
#    # classoption: [paper=6in:9in,pagesize=pdftex,headinclude=on,footinclude=on,12pt]


# https://quarto.org/docs/reference/formats/pdf.html


citation:
    type: webpage
    container-title: Patoloji Atlası
    url: "https://www.histopathologyatlas.com/"


editor: source

