project:
  type: book
  output-dir: _epub_word_EN
  resources:
    - "CITATION.cff"
    - images
    - screenshots
    - files
    - "script.js"
    - "webpages.js"
    - "webpages.txt"
    - "headerEN.html"


execute:
  freeze: auto

lang: en

book:
  title: "Histopathology Atlas"
  subtitle: "Atlas of Pathology with Whole Slide Images"
  author:
   - name: "Serdar Balcı"
     url: "https://www.serdarbalci.com"
     affiliation: "Memorial Pathology"
     affiliation-url: "https://patoloji.memorial.com.tr/"
     orcid: "0000-0002-7852-3851"
   - name: Pathologists, Assistants and Technicians
     affiliation: "Memorial Pathology & Other Institutions"
     affiliation-url: "https://www.histopathologyatlas.com/authors.html"
  description: |
    Atlas of Pathology with Whole Slide Images
    Histopathology Atlas and Notes for Medical Students: See and Learn
    Atlas of Histopathology
    Notes for Pathology
    Pathology Lecture Notes and Histopathology Atlas is being prepared from Memorial Pathology Archive and collaborators from other institutions.
  abstract: |
    Atlas of Pathology with Whole Slide Images
    Histopathology Atlas and Notes for Medical Students: See and Learn
    Pathology Lecture Notes and Histopathology Atlas is being prepared from Memorial Pathology Archive and collaborators from other institutions.
    If you want to contribute, please [contact us](https://www.histopathologyatlas.com/contributions.html).
  date: last-modified
  image: images/coverEN.png
  output-file: "HistoPatology-Atlas"
  cover-image: images/Histopathology-Atlas-ebook-cover.png
  site-url: https://histopathologyatlas.com/
  # repo-url: https://github.com/histopathologyatlas/histopathologyatlas.github.io
#  google-analytics: "G-7BT7Q4FLT9"
#  repo-branch: main
#  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
#   downloads: [epub, pdf, docx]
  search:
    location: navbar
    type: overlay
    copy-button: true
  sidebar:
    style: floating
    search: true
#   navbar:
#     title: "Pathology Atlas"
#     logo: images/coverEN.png
#     search: true
#     pinned: false
#     collapse: true
#     right:
#       - icon: github
#         href: https://github.com/patolojiatlasi
  open-graph: true
  # locale: tr_TR
  # site-name: Pathology Atlas
  twitter-card:
    creator: "%40serdarbalci"
    site: "%40patolojinotlari"
  page-navigation: true
  page-footer:
    border: true
    background: light
    left: "Copyright 2022, patolojiAI"
    # right:
    #   - icon: github
    #     href: https://github.com/patolojiatlasi
    #   - icon: github
    #     href: https://github.com/pathologyatlas
    #   - icon: twitter
    #     href: https://twitter.com/patolojinotlari
    #   - icon: globe2
    #     href: https://www.patolojinotlari.com
    #   - icon: globe2
    #     href: https://serdarbalci.com
  chapters:
    - text: "Home Page"
      href: index.qmd
    - text: "Introduction"
      href: introduction_epub_word_EN.qmd
    - part: "---"
    - part: "General Pathology"
      chapters:
        - text: "Techniques Used in Pathology"
          href: techniques_epub_word_EN.qmd
        - text: "Intracellular Accumulations"
          href: intracellular-accumulations_epub_word_EN.qmd
        - text: "Extracellular Accumulations"
          href: extracellular-accumulations_epub_word_EN.qmd
        - text: "Cellular Injury"
          href: cell-injury_epub_word_EN.qmd
#         - text: "Hemodynamic Disorders"
#           href: hemodinamik-bozukluklar_epub_word_EN.qmd
        - text: "Ischemia and Necrosis"
          href: ischemia-necrosis_epub_word_EN.qmd
        - text: "Congestion"
          href: congestion_epub_word_EN.qmd
        # - text: "Inflammation"
        #   href: inflamasyon_epub_word_EN.qmd
        - text: "Amyloidosis"
          href: amyloidosis_epub_word_EN.qmd
        - text: "Repair Mechanisms"
          href: repair_epub_word_EN.qmd
        - text: "Erosion"
          href: erosion_epub_word_EN.qmd
    - part: "Inflamation"
      chapters:
        - text: "Acute inflammation"
          href: acute-inflammation_epub_word_EN.qmd
        - text: "Chronic inflammation"
          href: chronic-inflammation_epub_word_EN.qmd
        - text: "Granulamatous inflammation"
          href: granulamatous-inflammation_epub_word_EN.qmd
        # - inflamasyon_epub_word_EN.qmd
#     - part: "Infectious Diseases"
#       chapters:
#         - text: "Viruses"
#           href: virus_epub_word_EN.qmd
#         - text: "Bacteria"
#           href: bacteria_epub_word_EN.qmd
#         - text: "Fungi"
#           href: fungi_epub_word_EN.qmd
#         - text: "Parasites"
#           href: parasites_epub_word_EN.qmd
#     - part: "Neoplasia, Tumor Pathology Basics"
#       chapters:
#         - text: "Benign Tumors"
#           href: benign_epub_word_EN.qmd
#         - text: "Hamartoma"
#           href: hamartoma_epub_word_EN.qmd
#         - text: "Heterotopia"
#           href: heterotopia_epub_word_EN.qmd
#         - text: "Metaplasia"
#           href: metaplasia_epub_word_EN.qmd
#         - text: "Carcinogenesis"
#           href: carcinogenesis_epub_word_EN.qmd
#         - text: "The properties of Malignant Tumors"
#           href: malignant_epub_word_EN.qmd
#         - text: "Metastasis"
#           href: metastasis_epub_word_EN.qmd
#         - text: "Tumor Spread to Other Organs"
#           href: tumor-spread_epub_word_EN.qmd
#     - part: "Prognostic Morphologic Features of Neoplasms"
#       chapters:
#         - text: "Venous Invasion"
#           href: venous-invasion_epub_word_EN.qmd
#         - text: "Extramural Venous Invaasion"
#           href: extramural-venous-invasion_epub_word_EN.qmd
#     - part: "Hematopathology"
#       chapters:
# #        - hematopatoloji_epub_word_EN.qmd
#         - text: "Hodgkin Lymphoma"
#           href: hodgkin_epub_word_EN.qmd
#     - part: "Gastrointestinal System"
#       chapters:
#         - gastro_epub_word_EN.qmd
#         - text: "Esophagus"
#           href: esophagus_epub_word_EN.qmd
#         - text: "Stomach"
#           href: stomach_epub_word_EN.qmd
#         - text: "Gastritis"
#           href: gastritis_epub_word_EN.qmd
#         - text: "Duodenum"
#           href: duodenum_epub_word_EN.qmd
#         - text: "Colon"
#           href: colon_epub_word_EN.qmd
#         - text: "Crohn's Disease"
#           href: crohn_epub_word_EN.qmd
#     - part: "Liver"
#       chapters:
#         - text: "Liver Tumors"
#           href: liver_epub_word_EN.qmd
#         - text: "Benign Liver Tumors"
#           href: benign-liver-tumors_epub_word_EN.qmd
#     - part: "Pancreatobiliary system"
#       chapters:
#         - text: "Pancreas"
#           href: pancreas_epub_word_EN.qmd
#         - text: "Pancreas Ductal Adenocarcinoma"
#           href: pdac_epub_word_EN.qmd
#         - text: "Gallbladder"
#           href: gallbladder_epub_word_EN.qmd
#         - text: "Ampulla of Vater"
#           href: ampulla-vater_epub_word_EN.qmd
#     - part: "Lung"
#       chapters:
#         - text: "Neuroendocrine"
#           href: neuroendocrine_epub_word_EN.qmd
#     - part: "Mezotel"
#       chapters:
#         - text: "Abdomen"
#           href: mesothelial_epub_word_EN.qmd
#     - part: "Gynecopathology"
#       chapters:
#         - text: "Gynecopathology"
#           href: gynecologic_epub_word_EN.qmd
#         - text: "Genital System"
#           href: genital_epub_word_EN.qmd
#         - text: "Cervix"
#           href: cervix_epub_word_EN.qmd
#         - text: "Endometrium"
#           href: endometrium_epub_word_EN.qmd
#         - text: "Endometriosis"
#           href: endometriosis_epub_word_EN.qmd
#     - part: "Uropathology"
#       chapters:
#         - text: "Uropathology"
#           href: urinary_epub_word_EN.qmd
#         - text: "Kidney Tumors / Renal Tumors"
#           href: kidney_epub_word_EN.qmd
#         - text: "Prostate"
#           href: prostate_epub_word_EN.qmd
#     - part: "Endocrine System"
#       chapters:
#         - text: "Pituitary Adenoma"
#           href: pituitary_epub_word_EN.qmd
#     # - part: "Breast"
#     #   chapters:
#     #     - text: "Breast Tumors"
#     #       href: meme.md
#     - part: "Head and Neck"
#       chapters:
#         - text: "Nasopharynx"
#           href: nasopharynx_epub_word_EN.qmd
#         - text: "Ear"
#           href: ear_epub_word_EN.qmd
#         - text: "Salivary Gland"
#           href: salivary_epub_word_EN.qmd
#     - part: "Central Nervous System"
#       chapters:
#         - text: "Glioma"
#           href: glioma_epub_word_EN.qmd
#         - text: "Meningioma"
#           href: meningioma_epub_word_EN.qmd
#         - text: "Vascular Lesions"
#           href: cns-vascular_epub_word_EN.qmd
#     - part: "Bone"
#       chapters:
#         - text: "Bone Tumors"
#           href: bone_epub_word_EN.qmd
#     - part: "Soft Tissue"
#       chapters:
#         - text: "Adipose Tissue"
#           href: adipose_epub_word_EN.qmd
#     - part: "Pediatric and Perinatal"
#       chapters:
#         - text: "Placenta"
#           href: placenta_epub_word_EN.qmd
#     - part: "---"
#     - part: "Special Collections"
#       chapters:
#         - text: "GBDAtlas"
#           href: gbd_epub_word_EN.qmd
#         - text: "Hacettepe Case of Month"
#           href: hacettepecom_epub_word_EN.qmd
#         - text: "BSAtlas"
#           href: bs_epub_word_EN.qmd
#         - text: "ICEtlas"
#           href: ice_epub_word_EN.qmd
#         - text: "Similar Websites"
#           href: wsi_epub_word_EN.qmd
    - part: "---"
    - references_epub_word_EN.qmd
    - part: "---"
  appendices:
    - text: "Authors and Contributors"
      href: authors_epub_word_EN.qmd
    # - yonetim-gelistirme.md
    - text: "Contributions are welcome"
      href: contributions_epub_word_EN.qmd
    - text: "Comments are welcome"
      href: comments_epub_word_EN.qmd
    # - text: "List"
    #   href: listing_epub_word_EN.qmd
    # - listing2_epub_word_EN.qmd

format:

  epub:
    toc: true
    epub-cover-image: images/coverEN.png
    execute:
      warning: false
    css:
      epub.css
    theme:
      light: flatly
      dark: darkly
    page-layout: full
    # grid:
    #   body-width: 1800px # default 900px
    # self-contained: false
    # anchor-sections: true
    # link-external-icon: true
    # link-external-newwindow: true
    # link-external-filter: '(^(?:http:|https:)\/\/www\.histopathologyatlas\.com\/)|(^(?:http:|https:)\/\/www\.patolojiatlasi\.com\/)|(^(?:http:|https:)\/\/images.patolojiatlasi\.com\/)|(^(?:http:|https:)\/\/pathologyatlas\.github\.io\/)|(^(?:http:|https:)\/\/patolojiatlasi\.github\.io\/)'
    # citations-hover: true
    # footnotes-hover: true
    # number-depth: 2
    # include-in-header:
    #   - text: |
    #       <script src="script.js"></script>
    #       <script src="webpages.js"></script>
    #   - file: "./headerTR.html"



# https://quarto.org/docs/reference/formats/epub.html



  docx:
    toc: true
    section-numbers: true
    highlight-style: github
    toc-depth: 2
    toc-title: "İçindekiler"
    number-sections: true
    number-depth: 2
    execute:
      warning: false
    # theme:
    #   light: flatly
    #   dark: darkly
    # page-layout: full
    # grid:
    #   body-width: 1800px # default 900px
    # cover-image: images/coverTR.png
    # css: styles.css
    # self-contained: false
    # anchor-sections: true
    # link-external-icon: true
    # link-external-newwindow: true
    # link-external-filter: '(^(?:http:|https:)\/\/www\.histopathologyatlas\.com\/)|(^(?:http:|https:)\/\/www\.patolojiatlasi\.com\/)|(^(?:http:|https:)\/\/images.patolojiatlasi\.com\/)|(^(?:http:|https:)\/\/pathologyatlas\.github\.io\/)|(^(?:http:|https:)\/\/patolojiatlasi\.github\.io\/)'
    # citations-hover: true
    # footnotes-hover: true
    # include-in-header:
    #   - text: |
    #       <script src="script.js"></script>
    #       <script src="webpages.js"></script>
    #   - file: "./headerTR.html"

# https://quarto.org/docs/output-formats/ms-word.html
# https://quarto.org/docs/reference/formats/docx.html



citation:
    type: webpage
    container-title: Patoloji Atlası
    url: "https://www.histopathologyatlas.com/"


editor: source

