project:
  type: book
  output-dir: _EN
  resources:
    - "CITATION.cff"
    - images
    - img
    - screenshots
    - openseadragon
    - annotorious
    - files
    - "script.js"
    - "webpages.js"
    - "webpages.txt"
    - "headerEN.html"


execute:
  freeze: auto

lang: en

book:

  title: "Histopathology Atlas"
  subtitle: "Atlas of Pathology with Whole Slide Images"
  author:
   - name: "Serdar Balcı"
     url: "https://www.serdarbalci.com"
     affiliation: "Memorial Pathology"
     affiliation-url: "https://patoloji.memorial.com.tr/"
     orcid: "0000-0002-7852-3851"
   - name: Pathologists, Assistants and Technicians
     affiliation: "Memorial Pathology & Other Institutions"
     affiliation-url: "https://www.histopathologyatlas.com/authors.html"
  description: |
    Atlas of Pathology with Whole Slide Images. 
    Histopathology Atlas and Notes for Medical Students. 
    Atlas of Histopathology. 
    Notes for Pathology. 
    Virtual Microscope. 
    Virtual Microscopy. 
    Online Pathology Atlas. 
    Pathology Lecture Notes and Histopathology Atlas is being prepared from Memorial Pathology Archive and collaborators from other institutions.
  abstract: |
    Atlas of Pathology with Whole Slide Images
    Histopathology Atlas and Notes for Medical Students
    Pathology Lecture Notes and Histopathology Atlas is being prepared from Memorial Pathology Archive and collaborators from other institutions.
    If you want to contribute, please [contact us](https://www.patolojiatlasi.com/contributions.html).
  date: last-modified
  image: images/coverEN.png
  output-file: "HistoPatology-Atlas"
  cover-image: images/coverEN.png
  site-url: https://histopathologyatlas.com/
  # repo-url: https://github.com/histopathologyatlas/histopathologyatlas.github.io
#  google-analytics: "G-7BT7Q4FLT9"
#  repo-branch: main
#  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
#   downloads: [epub, pdf, docx]
  search:
    location: navbar
    type: overlay
    copy-button: true
  sidebar:
    style: floating
    search: true
#   navbar:
#     title: "Pathology Atlas"
#     logo: images/coverEN.png
#     search: true
#     pinned: false
#     collapse: true
#     right:
#       - icon: github
#         href: https://github.com/patolojiatlasi
  open-graph: true
  # locale: tr_TR
  # site-name: Pathology Atlas
  twitter-card:
    creator: "%40serdarbalci"
    site: "%40patolojinotlari"
  page-navigation: true
  page-footer:
    border: true
    background: light
    left: "Copyright 2022, patolojiAI"
    # right:
    #   - icon: github
    #     href: https://github.com/patolojiatlasi
    #   - icon: github
    #     href: https://github.com/pathologyatlas
    #   - icon: twitter
    #     href: https://twitter.com/patolojinotlari
    #   - icon: globe2
    #     href: https://www.patolojinotlari.com
    #   - icon: globe2
    #     href: https://serdarbalci.com
  chapters:
    - text: "Home Page"
      href: index.qmd
    - text: "Introduction"
      href: introduction.qmd
    - part: "---"
    - part: "General Pathology"
      chapters:
        - text: "Techniques Used in Pathology"
          href: techniques.qmd
        - text: "Intracellular Accumulations"
          href: intracellular-accumulations.qmd
        - text: "Extracellular Accumulations"
          href: extracellular-accumulations.qmd
        - text: "Cellular Injury"
          href: cell-injury.qmd
#         - text: "Hemodynamic Disorders"
#           href: hemodinamik-bozukluklar.qmd
        - text: "Ischemia and Necrosis"
          href: ischemia-necrosis.qmd
        - text: "Congestion"
          href: congestion.qmd
        # - text: "Inflammation"
        #   href: inflamasyon.qmd
        - text: "Amyloidosis"
          href: amyloidosis.qmd
        - text: "Repair Mechanisms"
          href: repair.qmd
        - text: "Erosion"
          href: erosion.qmd
    - part: "Inflamation"
      chapters:
        - text: "Acute inflammation"
          href: acute-inflammation.qmd
        - text: "Chronic inflammation"
          href: chronic-inflammation.qmd
        - text: "Granulamatous inflammation"
          href: granulamatous-inflammation.qmd
        # - inflamasyon.qmd
    - part: "Infectious Diseases"
      chapters:
        - text: "Viruses"
          href: virus.qmd
        - text: "Bacteria"
          href: bacteria.qmd
        - text: "Fungi"
          href: fungi.qmd
        - text: "Parasites"
          href: parasites.qmd
    - part: "Neoplasia, Tumor Pathology Basics"
      chapters:
        - text: "Benign Tumors"
          href: benign.qmd
        - text: "Hamartoma"
          href: hamartoma.qmd
        - text: "Heterotopia"
          href: heterotopia.qmd
        - text: "Metaplasia"
          href: metaplasia.qmd
        - text: "Carcinogenesis"
          href: carcinogenesis.qmd
        - text: "The properties of Malignant Tumors"
          href: malignant.qmd
        - text: "Metastasis"
          href: metastasis.qmd
        - text: "Tumor Spread to Other Organs"
          href: tumor-spread.qmd
    - part: "Prognostic Morphologic Features of Neoplasms"
      chapters:
        - text: "Venous Invasion"
          href: venous-invasion.qmd
        - text: "Extramural Venous Invaasion"
          href: extramural-venous-invasion.qmd
    - part: "Hematopathology"
      chapters:
#        - hematopatoloji.qmd
        - text: "Hodgkin Lymphoma"
          href: hodgkin.qmd
    - part: "Gastrointestinal System"
      chapters:
        - gastro.qmd
        - text: "Esophagus"
          href: esophagus.qmd
        - text: "Stomach"
          href: stomach.qmd
        - text: "Gastritis"
          href: gastritis.qmd
        - text: "Duodenum"
          href: duodenum.qmd
        - text: "Colon"
          href: colon.qmd
        - text: "Crohn's Disease"
          href: crohn.qmd
    - part: "Liver Pathology"
      chapters:
        # - text: "Liver Pathology"
        #   href: liver.qmd
        - text: "Liver Transplantation"
          href: liver-transplantation.qmd
        - text: "Benign Liver Tumors"
          href: benign-liver-tumors.qmd
        - text: "Malignant Liver Tumors"
          href: malignant-liver-tumors.qmd
    - part: "Pancreatobiliary system"
      chapters:
        - text: "Pancreas Tumors"
          href: pancreas.qmd
        # - text: "Pancreas Ductal Adenocarcinoma"
        #   href: pdac.qmd
        - text: "Gallbladder"
          href: gallbladder.qmd
        - text: "Ampulla of Vater"
          href: ampulla-vater.qmd
    - part: "Lung"
      chapters:
        - text: "Lung Tumors"
          href: lung.qmd
        - text: "Neuroendocrine"
          href: neuroendocrine.qmd
    - part: "Mezotel"
      chapters:
        - text: "Abdomen"
          href: mesothelial.qmd
    - part: "Gynecopathology"
      chapters:
        # - text: "Gynecopathology"
        #   href: gynecologic.qmd
        - text: "Genital System"
          href: genital.qmd
        - text: "Cervix"
          href: cervix.qmd
        - text: "Endometrium"
          href: endometrium.qmd
        - text: "Endometriosis"
          href: endometriosis.qmd
    - part: "Uropathology"
      chapters:
        - text: "Uropathology"
          href: urinary.qmd
        - text: "Kidney Tumors / Renal Tumors"
          href: kidney.qmd
        - text: "Prostate"
          href: prostate.qmd
    - part: "Endocrine System"
      chapters:
        - text: "Pituitary Adenoma"
          href: pituitary.qmd
    - part: "Breast"
      chapters:
        - text: "Breast Tumors"
          href: breast.qmd
    - part: "Head and Neck"
      chapters:
        - text: "Nasopharynx"
          href: nasopharynx.qmd
        - text: "Ear"
          href: ear.qmd
        - text: "Salivary Gland"
          href: salivary.qmd
    - part: "Central Nervous System"
      chapters:
        - text: "Glioma"
          href: glioma.qmd
        - text: "Meningioma"
          href: meningioma.qmd
        - text: "Vascular Lesions"
          href: cns-vascular.qmd
    - part: "Bone"
      chapters:
        - text: "Bone Tumors"
          href: bone.qmd
    - part: "Soft Tissue"
      chapters:
        - text: "Adipose Tissue"
          href: adipose.qmd
    - part: "Skin"
      chapters:
        - text: "Skin Diseases"
          href: skin.qmd
    - part: "Pediatric and Perinatal"
      chapters:
        - text: "Placenta"
          href: placenta.qmd
    - part: "---"
    - part: "Special Collections"
      chapters:
        - text: "GBDAtlas"
          href: gbd.qmd
        - text: "Hacettepe Case of Month"
          href: hacettepecom.qmd
        - text: "BSAtlas"
          href: bs.qmd
        - text: "ICEtlas"
          href: ice.qmd
        - text: "Similar Websites"
          href: wsi.qmd
    - part: "---"
    - references.qmd
    - part: "---"
  appendices:
    - text: "Authors and Contributors"
      href: authors.qmd
    - text: "Contributions are welcome"
      href: contributions.qmd
    - text: "Comments are welcome"
      href: comments.qmd
    - text: "Augmented Reality"
      href: augmented-reality.qmd
#    - text: "List"
#      href: listing.qmd
#    - listing2.qmd


# before_chapter_script: "./R/language.R"

# bibliography: references.bib
# # csl: citestyle.csl
highlight-style: pygments


comments:
  hypothesis: true
  utterances:
    repo: patolojiatlasi/patolojiatlasi.github.io
#   giscus:
#     repo: patolojiatlasi/patolojiatlasi.github.io
format:
  html:
    theme:
      light: flatly
      dark: darkly # cosmo
    page-layout: full
    grid:
      # sidebar-width: 300px
      body-width: 1800px # default 900px
      # margin-width: 300px
      # gutter-width: 1.5rem
    cover-image: images/coverEN.png
#    code-link: true
#    code-fold: true
#    code-tools: true
#    code-copy: true

#    fig-width: 8
#    fig-height: 4
    execute:
      warning: false
#    css: styles.css
    self-contained: false
    feed:
      type: rss
      path: feed.xml
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '(^(?:http:|https:)\/\/www\.histopathologyatlas\.com\/)|(^(?:http:|https:)\/\/www\.patolojiatlasi\.com\/)|(^(?:http:|https:)\/\/images.patolojiatlasi\.com\/)|(^(?:http:|https:)\/\/pathologyatlas\.github\.io\/)|(^(?:http:|https:)\/\/patolojiatlasi\.github\.io\/)'
    citations-hover: true
    footnotes-hover: true
    number-depth: 2
    # toc-title: "İçindekiler"
    include-in-header:
      - text: |
          <script src="script.js"></script>
          <script src="webpages.js"></script>
      - file: "./headerEN.html"
    feeds:
      rss: true

#   epub:
#     toc: true
#     epub-cover-image: images/coverEN.png
#     execute:
#       warning: false
#     css:
#       epub.css


#   pdf:
#     keep-tex: true
#     documentclass: scrbook
#     classoption: [paper=6in:9in,pagesize=pdftex,headinclude=on,footinclude=on,12pt]
#
# #    documentclass: scrreprt
#     toc: true
#     toc-depth: 2
#     toc-title: "İçindekiler"
#     number-sections: true
#     number-depth: 2
#     colorlinks: true
#     highlight-style: github
#     execute:
#       warning: false
#     include-in-header:
#       text: |
#         \usepackage{fvextra}
#         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
#         \areaset[0.50in]{4.5in}{8in}
#         \usepackage{titlesec}
#         \usepackage{svg}
#         \usepackage{transparent}
#         \usepackage{tikzfill}
#         \usepackage{sidenotes}
#         \usepackage{marginnote}
#         \usepackage{changepage}
#
#     include-before-body:
#       text: |
#         \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
#            showspaces = false,
#            showtabs = false,
#            breaksymbolleft={},
#            breaklines
#            % Note: setting commandchars=\\\{\} here will cause an error
#         }
#     fig-pos: 'H'

#   docx:
#     toc: true
#     section-numbers: true
#     highlight-style: github
#     toc-depth: 2
#     # toc-title: "İçindekiler"
#     number-sections: true
#     number-depth: 2


citation:
    type: webpage
    container-title: Histopathology Atlas Atlas of Pathology with Whole Slide Images
    url: "https://www.histopathologyatlas.com/"


editor: source


